name: paperfilter
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=20.2.4
  - python=3.8
  - jupyter=1.0.0
  - matplotlib=3.3.2
  - numpy=1.19.2
  - nbconvert=5.6.1
  - jupyter_contrib_nbextensions=0.5.1
  - requests=2.26.0
  - beautifulsoup4=4.10.0
  - pandas=1.3.4
  - tqdm=4.62.3